### ISSUE TITLE
Find an automatic solution for keeping indexes ordered and free from duplicates

### ISSUE THREAD

**Issue by myii** [saltstack/docs-hub#15]
While looking at the docs a little while back, I noticed that some of the indexes weren't sorted alphabetically.  Looked through the various indexes and found a few more places that were affected, as well as some duplicates that had slipped in.  Sent it through as a PR that's close to being merged:

* https://github.com/saltstack/salt/pull/56237

The point behind starting this issue is that it would be useful to find an automated solution for this, to order the items automatically and prevent any duplicates.

**Comment by mchugh19** [comment]
As @max-arnold suggested, this has been added to #55914
